### ISSUE TITLE
[PLAYGROUND PROJECT] Project #163

### ISSUE THREAD

**Issue by mattdesl** [ArtBlocks/artbot#103]
- Project Title: "Meridian"
- Project Size: 1000
- Project ID: 163
- Artist Channel ID: 833713318107545670 (#matt-deslauriers)
- Project Keyword: "meridian"

**Comment by jakerockland** [comment]
Awesome, thanks Matt for filing :) @ryley-o sending this your way!

**Comment by ryley-o** [comment]
This project was already added in PR #98. It just needs to be deployed.

**Comment by jakerockland** [comment]
Aha :) thank you! That is deployed now actually.

**Comment by jakerockland** [comment]
Oversight on my part.
