### ISSUE TITLE
Performance improvement - Quick return if message from unrecognized channel

### ISSUE THREAD

**Issue by ryley-o** [ArtBlocks/artbot#108]
Create a hashmap of valid Discord channelIDs to respond to, and immediately return if channel will not be responded to. This will result in less checking on every message on channels not being handled by artbot.

**Comment by Asupkay** [comment]
Is this causing the bot to be slow or what is the side effect of handling every message?

**Comment by ryley-o** [comment]
I think the only side effect is more processing than necessary. Jake might have stronger opinions, but seems like a very minor benefit.

**Comment by jakerockland** [comment]
Yeah would just be a minor performance improvement. May be a wontfix for now if we feel like it adds too much unnecessary complexity.

**Comment by Asupkay** [comment]
If the performance improvement is measurable and detectable by the user I'm definitely interested. I just want to make sure this doesn't become more annoying for us where we always have to remember to update the channelID list even though we're not seeing any improvement for the user.

**Comment by ryley-o** [comment]
I think it would be ~no measurable performance improvement for user unless there were so many messages coming in from unwatched channels that artbot started lagging 🤷‍♂️ 

We already specify all watched channels in `/ProjectConfig/projectBots.json`, so shouldn't cause any additional maintenance 😃

**Comment by Asupkay** [comment]
Hmmmm since the watched channels already exist might be worth it if it's super simple. I'll take a look tomorrow and see what I can do. Thanks for the explanation!

**Comment by Asupkay** [comment]
With the expansion to PBAB partners with #230 and #225 this may make a lot of sense. Should be a simple ticket that would be good for someone new.
