### ISSUE TITLE
Improve how artbot handles random token selection of partially minted projects

### ISSUE THREAD

**Issue by ryley-o** [ArtBlocks/artbot#142]
Currently, artbot selects a random `#?` token by using `0` and `Maximum Invocations` as the range for the project.

Ideally, it should use the range of `0` and `Invocations`, which can be known via artblocks subgraph, the artblocks project api, etc. This would prevent selection of non-existent tokens when a user queries `#?` of a project that is only partially minted.

**Comment by Asupkay** [comment]
Hi Ryley, is this still true? Looking at the RandomBot file I see the piece number is grabbed by running - `const pieceNumber = parseInt(Math.random() * projectData.invocations);`

**Comment by ryley-o** [comment]
Hey @Asupkay! 

if it helps, this is the problematic line: https://github.com/ArtBlocks/artbot/blob/abeb7363c923f2ed0d0f8e72b11853cb8260e842/Classes/ProjectBot.js#L48

I *think* this issue only affects curated and playground projects. Factory actually queries the our subgraph and sets each project bot's `editionSize` to the current number of invocations, and refreshes its cache every 60 mins.
https://github.com/ArtBlocks/artbot/blob/abeb7363c923f2ed0d0f8e72b11853cb8260e842/Classes/FactoryBot.js#L37

The solution is probably to do something similar for the curated and playground bots, which would allow us to remove some of the manually-entered `ProjectConfig/projectBots.json` fields that exist in our subgraph.

We could also change the name of that ProjectBot property from editionSize to numInvocations or something.
