### ISSUE TITLE
[Jiometory No Compute - ジオメトリ ハ ケイサンサレマセン] Project #232

### ISSUE THREAD

**Issue by Samsy** [ArtBlocks/artbot#174]
######################################################################

Please fill out the template below and then delete everything within the #'s here, it is purely informational for help filing this ticket.

For example, this is what it would look like Project 143, Phase by Loren Bednar:

- Project Title: "Jiometory No Compute - ジオメトリ ハ ケイサンサレマセン"
- Project Size: 1024
- Project ID: 232
- Artist Channel ID: 920399256454594652

Note: you can find the channel ID for a given channel by right-clicking it in Discord and selecting "Copy ID".

######################################################################

- Project Title: "Jiometory No Compute - ジオメトリ ハ ケイサンサレマセン"
- Project Size: 1024
- Project ID: 232
- Artist Channel ID: 920399256454594652

**Comment by ryley-o** [comment]
I plan to get to this by the end of the day
