### ISSUE TITLE
[CURATED PROJECT] Project #N

### ISSUE THREAD

**Issue by mpkoz** [ArtBlocks/artbot#183]
- Project Title: Chimera
- Project Size: 987
- Project ID: 233
- Artist Channel ID: 923461105374855188

**Comment by jakerockland** [comment]
@mchrupcala Sending this your way to grow the # of people within the team that know how to make these changes 😄 

@ryley-o would be a great person to help walk you through this if you're having trouble.

**Comment by mchrupcala** [comment]
@jakerockland no problem! I'll reach out to him so I don't miss any steps.

**Comment by mchrupcala** [comment]
Merged https://github.com/ArtBlocks/artbot/pull/184
