### ISSUE TITLE
`arbot` stopped responding to commands on Tyler Hobbs server

### ISSUE THREAD

**Issue by jonkensta** [ArtBlocks/artbot#188]
`arbot` has stopped responding to `#` commands on the following text channels:

- `sales-chat`
- `the-place-to-be`
- `fidenza-owners`
- `incomplete-control`

It appears to be still publishing the sales feed, however, as the last sales feed item was published today at 12:49PM CST and it is 13:24PM CST now.

**Comment by jakerockland** [comment]
This is due to an API outage on OpenSea's end, we're currently looking into resolving this.

Closing this bug not because it is already fixed, but because we're already monitoring this and can't immediately resolve on our end.

cc @Jbern16

**Comment by jonkensta** [comment]
@jakerockland okay, thank you

**Comment by Jbern16** [comment]
fixed, no authenticated requests seem broken on OS side, we added the api key and looks like we are back in business 🚀
