### ISSUE TITLE
[COSMIC REEF] Project #250

### ISSUE THREAD

**Issue by sarahrossien** [ArtBlocks/artbot#192]
- Project Title: Cosmic Reef
- Project Size: 1024
- Project ID: 250
- Artist Channel ID: 933419567722664016

**Comment by jakerockland** [comment]
@ab-hxm @Jbern16 sending this your way for further triage.

**Comment by ab-hxm** [comment]
👀

**Comment by ab-hxm** [comment]
duplicate of: https://github.com/ArtBlocks/artbot/pull/195
