### ISSUE TITLE
ArtBot OTC Response in #for-sale-listings & #trade-swaps

### ISSUE THREAD

**Issue by pompeyplottinAB** [ArtBlocks/artbot#320]
ArtBot to automatically reply when "OTC" is mentioned in either #for-sale-listings or #trade-swaps channels. 

“If participating in an OTC trade, please take extra caution to ensure a safe transaction! We have a few trusted options pinned in the <#874066035618250752> channel.

For an OTC sale, we also encourage sending the Artist and Art Blocks royalties. More info can be found here <https://discord.com/channels/411959613370400778/797930335874449408/1004904448583278712> in <#797930335874449408>.

**Comment by jakerockland** [comment]
This one is a smol ask, @grantoesterling would you be open to taking this on sometime next week if you have bandwidth?
