### ISSUE TITLE
#? <ens / wallet address>

### ISSUE THREAD

**Issue by grantoesterling** [ArtBlocks/artbot#338]
Suggested by [dbochman here](https://discord.com/channels/411959613370400778/830924481627291709/1014210578971115712) (and probably many other people I am forgetting

`#? <ens/wallet addy>` to get random piece from a user's collection - can just hit hasura for this info probably, no need for any web3 queries

**Comment by jakerockland** [comment]
This is very cool idea 🔥 I dig it.
