### ISSUE TITLE
Include collection type in sales event (e.g. "Curated")

### ISSUE THREAD

**Issue by jakerockland** [ArtBlocks/artbot#346]
Based on feedback from Art Blocks Discord.

<img width="742" alt="Screen Shot 2022-09-14 at 12 02 50 PM" src="https://user-images.githubusercontent.com/8602661/190228994-9275fd68-ec6e-40d3-b6be-f91ae5dfa90a.png">

**Comment by grantoesterling** [comment]
Probs will have to hit Hasura for this data. might be worth having some sort of map of Project -> Curation status that gets loaded on start (as part of ArtIndexerBot I imagine)

**Comment by jakerockland** [comment]
> might be worth having some sort of map of Project -> Curation status that gets loaded on start (as part of ArtIndexerBot I imagine)

This isn't too expensive/complicated, but may be a pain to maintain. I don't have a super strong opinion here. Also could query token #0 for a given project (or the specific token) via token API to have this info re: curation status as it is returned by the token API.
