### ISSUE TITLE
Staysafe? Command Update

### ISSUE THREAD

**Issue by pompeyplottinAB** [ArtBlocks/artbot#348]
Hey,

Could we please update the first line of the Staysafe? reply to:

"**Always** double check who you are trading with! Discord handles can appear to be similar so verify a user by checking their **User ID**. How to here <1021586607188496465>"

Then can we add a new line below "If something seems..." and above "Official Art Blocks Links:"

"Stay up to date and report scams in #scam-reporting <1019738320303030345>"

**Comment by jakerockland** [comment]
@grantoesterling sending this your way if it is a quickfix ser.
