### ISSUE TITLE
Arbot pulling a random 'animated' piece aka '#? Animated'

### ISSUE THREAD

**Issue by PonyoAB** [ArtBlocks/artbot#496]
We had a few community members request that artbot have the ability to pull a random 'animated' piece aka '#? Animated'. other similar artbot requests include:

#? interactive
#? evolving
#? audio
#? responsive

all of these are keywords that highlight the style of work that can be used in a project description page. screenshot attached:
![Screenshot 2023-04-12 at 12 06 00 PM](https://user-images.githubusercontent.com/86338251/231516866-35016cf5-a713-4451-803b-2eed58dba2cf.png)

thanks,
massoud

**Comment by jakerockland** [comment]
cc @Asupkay – feels like a good item to take into the backlog for the Collector pod to prioritize as your team determines makes sense.

@grantoesterling leaving you as the assignee here and removing myself for now.
